development:
  adapter: async
  channel_prefix: development_shards_of_the_grid


test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: production_shards_of_the_grid
  ssl: true